### ISSUE TITLE
Need CFT like f5-existing-stack-across-az-cluster-byol-3nic-bigip.template with no public mgmt IP

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-aws-cloudformation#60]
## Description
Describe the problem you're having or the enhancement you'd like to request.

There is no CFT that provides for HA across AZs, 3 NICs, and BYOL that doesn't also require a public mgmt IP address.  This is done on most other configurations with the "Production" template variant, but there isn't one is equivalent to f5-existing-stack-across-az-cluster-byol-3nic-bigip.template.

This issue is also open with support on SR#C2848912 | | CloudFormation templates can't change vol size or remove Public Mgmt IP

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
2 - Can't go live until this is resolved
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by f5-gasingh** [comment]
This issue was resolved through F5 support.

**Comment by C0missar** [comment]
No, it was not.

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com
http://www.sherwin-williams.com


-----"Ganimat Singh" <notifications@github.com> wrote: -----
To: "F5Networks/f5-aws-cloudformation" <f5-aws-cloudformation@noreply.github.com>

**Comment by codygreen** [comment]
@f5-gasingh please re-open this issue.  It was not resolved.

**Comment by f5-gasingh** [comment]
Re-opening this issue as we research this case. Thank you.

**Comment by C0missar** [comment]
I'm also having trouble understanding how to connect to the prod templates that do exist, as they don't appear to present a private IP for management.

**Comment by crosbygw** [comment]
You are right, the production stacks do not appear to include an output for the management address. I have added this as an improvement, and is being tracked internal as ESECLDTPLT-895.

In the meantime, you can look at the ip address assigned to int eth0 to determine the management ip address.

**Comment by C0missar** [comment]
I don't know how to do that.  int eth0 does not appear to be referenced in the template or output.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 5.7.1](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.7.1).
